title: Your awesome title
author: GitHub User
email: your-email@domain.com
show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: <!--excerpt-->

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Liu Dingxin
  tagline: Lab Designer. IoT Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: liudingxin
    github:  liudingxin
    #linkedIn: in/thelehhman
    #rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

gems: [jekyll-paginate]

paginate: 5
paginate_path: "page:num"